### ISSUE TITLE
Inserting a row/column always put it after the first one

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/slate-edit-table#12]
Instead of inserting after the current one, it always insert after the first one.

**Comment by Soreine** [comment]
Weird. I could not reproduce the bug on the demo, and [this passing test](https://github.com/GitbookIO/slate-edit-table/tree/master/tests/insert-column) inserts a column after two others. How have you met this bug ?

**Comment by Soreine** [comment]
OK I noticed it in our app.

**Comment by Soreine** [comment]
I fixed it in our app.

# Cause

Our tables have a tooltip on hover, with actions such as "Insert column".
Clicking on the tooltip would move the focus (incidentally to the first cell).

# Fix

Adding `onMouseDown` to our actions buttons prevent from changing the focus:

```
onMouseDown(e) {
    e.preventDefault(); // prevents affecting the focus
}
```
