### ISSUE TITLE
Normalization: enforce rows / cells only inside table?

### ISSUE THREAD

**Issue by jasonphillips** [GitbookIO/slate-edit-table#13]
(Excellent plugin; this one was really the tipping point in my switch to Slate after struggling to handle table abstractions myself within the quirks and API limitations of Draft)

I see that the schema enforces certain normalization rules (in the form of "parent may only contain children of type x"; ie, tables may contain rows, rows may contain cells) but I'm occasionally seeing a situation where a paste operation by the user ends up inserting rows without an enclosing table. I haven't fully explored all the schema normalization / transformation operations available in slate's current iteration, but would it be possible to include rules of the type "child can only appear within parent type Y" so that these table-fragment paste operations would automatically wrap an enclosing table tag when needed?

**Comment by SamyPesse** [comment]
@jasonphillips Yes, you're right.

We are going to fix this in the upcoming release.
