### ISSUE TITLE
consider adding keyword support to inserting

### ISSUE THREAD

**Issue by ianstormtaylor** [GitbookIO/slate-edit-table#24]
Right now you can either specify the index exactly, or omit it to mean "after the current one". I think it would be nice if there was an option for keywords:

```js
'before' // before the current column/row
'after' // after the current column/row
'start' // at the start of the columns/rows
'end' // at the end of the columns/rows
```

```js
insertColumn(transform, 'before')
insertRow(transform, 'end')
```

The `'start'` keyword is equivalent to `0`, but all of the others are harder to compute in the moment, and could save lots of extra work.

**Comment by Soreine** [comment]
It might be good to expose `TablePosition` utility somehow https://github.com/GitbookIO/slate-edit-table/blob/master/lib/TablePosition.js
