### ISSUE TITLE
table header support?

### ISSUE THREAD

**Issue by ianstormtaylor** [GitbookIO/slate-edit-table#25]
Hey @Soreine @SamyPesse not sure if you've already considered this, but it would be awesome to add support for table headers, for labelling the columns.

**Comment by SamyPesse** [comment]
With `markup-it` and the GitBook Editor, we consider the first row as the header and style it differently.

I'm not sure changing the data structure for a table will be a good idea (it'll make the transforms more complex, etc), but we're always open to suggestion :)

**Comment by ianstormtaylor** [comment]
Ah nice, I hadn't even considered that haha. I'll try out that with my serializer. Thanks!
