### ISSUE TITLE
Pressing Enter in a cell should split the text

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/slate-edit-table#3]

**Comment by Soreine** [comment]
Meaning, like Google Docs for example, to insert a newline in the cell text ?

What about acting like Google Sheets, by moving to the cell below ?

**Comment by SamyPesse** [comment]
Yes it should move to the cell below (See #4)

But If my table is (cursor is `<>`):

```
| aa | bb |
| cc | d<>d |
```

Pressing enter should result in:

```
| aa | bb |
| cc | d |
| | <>d |
```

**Comment by zhujinxuan** [comment]
How about allowing soft break in the table if enter is pressed in between?

I would like to submit a PR for that.

**Comment by wasabigeek** [comment]
I'm guessing any progress on this will depend on the implementation of https://github.com/GitbookIO/slate-edit-table/pull/69?
