### ISSUE TITLE
Issue when deleting a table and the document contains nothing else

### ISSUE THREAD

**Issue by mahlero** [GitbookIO/slate-edit-table#34]
**Do you want to request a feature or report a bug?**

Bug

**What's the current behaviour?**

1. Go to https://gitbookio.github.io/slate-edit-table/
2. Delete everything
3. Insert a table
4. Delete that table

From this point on, any subsequent editing fails.

The reason seems to be that the document is left without any nodes.

**What's the expected behavior?**

The editor should contain the default empty node.

My workaround right now is to manually insert an empty paragraph _before_ deleting the table.

**Comment by Soreine** [comment]
Isn't it a bug that any Slate plugin would have ? If you select all your document and delete it, what should remains ? I think it's up to Slate to determine that.

**Comment by SamyPesse** [comment]
Not related to this plugin, you can have your own normalization rules to ensure the document is never empty.
