### ISSUE TITLE
How to pass props / data to node table_row?

### ISSUE THREAD

**Issue by mfbx9da4** [GitbookIO/slate-edit-table#36]
e.g. I want to make a header row

```js
const TableSchema = {
    nodes: {
       ...
        table_row:  props => {
          return props.node.get('data').get('isHeader') ?
            <th {...props.attributes}>{props.children}</th> :
            <tr {...props.attributes}>{props.children}</tr>
        },
     ...
};
```

I should be able to do something like 

```js
// set row as header
plugin.transforms.setRowData(state.transform(), { isHeader: true })
      .apply()
```

I also may want to have other types of data e.g. `isSuccessRow`, `isSortable`, `cellColor`, `onClickCell` or some other formatting of the row / cell.

To have this kind of flexibility, I believe that a method would have to be exposed which would allow for any kind of props to be passed to the row / cell / table node

```js
    transform.setNodeByKey(table.key, {
        data: data
    });
```

**Comment by YurkaninRyan** [comment]
So it seems like you can do this, but some methods will wipe it clean.  For example insertColumn seems to reset all data

**Comment by mfbx9da4** [comment]
reset all row data? or just cell data? do we lose the alignment state also then on adding a new column?

**Comment by YurkaninRyan** [comment]
@mfbx9da4 From what I can tell, you will never lose alignment state, it's just many times in the codebase it setsNodeByKey with only align data instead of merging with what is already there

Effectively wiping any custom data

**Comment by Soreine** [comment]
I guess the correct way of dealing with data is to

```js
transform.setNodeByKey(table.key, {
        data: table.data.merge(newDataObject)
});
```

You should do this to set data on tables/rows/cells. And we should be careful to merge as well everytime.

**Comment by Soreine** [comment]
#43 should have improved the situation by not wiping any data you set on your table, rows, or cells.
Let me know if you're still having issues
