### ISSUE TITLE
Allow for non typeCell blocks in a cell

### ISSUE THREAD

**Issue by CameronAckermanSEL** [GitbookIO/slate-edit-table#42]
The consumers of an editor I am producing requires table cells to 
1. be multiline
2. allow images
3. allow block quotes
4. allow code blocks

The rules in makeSchema block these. From what I can tell, it's to maintain some sort of data integrity with what goes into the cell (which is a good thing) but it's not flexible enough to meet some other more... unusual :) use cases. 

It would be nice if we could specify acceptable types of blocks that may go into a table cell as part of the plugin configuration.

**Comment by CameronAckermanSEL** [comment]
this would require a change to isSelectionInTable to check parents of selected blocks to see if they sit in a table cell

**Comment by Soreine** [comment]
Let's merge this issue with #45 :)
