### ISSUE TITLE
Question: Allow blocks inside a cell? 

### ISSUE THREAD

**Issue by mfbx9da4** [GitbookIO/slate-edit-table#45]
Presumably not something slate-edit-table are looking to support?

Theoretically if I were to fork off of `slate-edit-table` and support blocks what work would be required?
  - Remove [noBlocksWithinCell](https://github.com/GitbookIO/slate-edit-table/blob/master/lib/makeSchema.js#L30) constraint, anything else

**Comment by Soreine** [comment]
The goal is the same as the feature request in #42 

So yeah, we should:

- Add an option for allowing blocks in cells
- Adapt `noBlocksWithinCell` rule to be an option
- Adapt `isSelectionInTable` to not assume the direct parent should be a cell

**Comment by mfbx9da4** [comment]
Also will need to change 

- [Creation of cells](https://github.com/jasonphillips/slate-deep-table/blob/master/lib/createCell.js)

slate-deep-table does a pretty good job!

**Comment by Soreine** [comment]
Indeed. I think we already mentioned it, that this is not in the scope of this project. We will probably not implement it ourselves, but we would be glad to accept a PR for it, and maintain it as an option for the plugin.
