### ISSUE TITLE
Schema no longer supports rules

### ISSUE THREAD

**Issue by RyanMacG** [GitbookIO/slate-edit-table#46]
As of last week/version 0.28.0 the Schema object no longer supports rules as it did previously - more info here https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#0280--october-25-2017

The line that seems to be causing this issue is - https://github.com/GitbookIO/slate-edit-table/blob/2bc336801673daec7819504847652f66abd13876/lib/makeSchema.js#L12

**Comment by Soreine** [comment]
Closed by #47
