### ISSUE TITLE
onKeyUp is broken

### ISSUE THREAD

**Issue by YurkaninRyan** [GitbookIO/slate-edit-table#53]
@Soreine it's just a small typo https://github.com/GitbookIO/slate-edit-table/blob/master/lib/handlers/onKeyDown.js#L18

**Comment by zhujinxuan** [comment]
Why not just submit a PR?

**Comment by CameronAckermanSEL** [comment]
Another thing that's busted about this is that it uses "UpArrow" in a couple of places.

https://github.com/GitbookIO/slate-edit-table/blob/060ce397ab59341d8997b834a524ccddfb7494ec/lib/handlers/onUpDown.js

Some constants might be a good idea.

**Comment by zhujinxuan** [comment]
https://github.com/GitbookIO/slate-edit-table/pull/55

POI!

**Comment by CameronAckermanSEL** [comment]
This should be closed now thanks to @zhujinxuan
