### ISSUE TITLE
Would you like width for table_cell?

### ISSUE THREAD

**Issue by zhujinxuan** [GitbookIO/slate-edit-table#56]
Hi, recently I am trying to add `presetWidth` for `table.data` and `percentWidth` for` cell.data`, and I am deciding whether I shall put it in another plugin (a plugin of slate-edit-table plugin lol).

Just wondering would you like to merge the feature into this plugin when completed?  If you like, I will work directly on this plugin and submit as a PR.

**Comment by Soreine** [comment]
I think it's best to keep it separate. You can make a separate plugin package for that, or just share the extra code that you added to your app. But this plugin should not directly implement this.

However, please report back if you need any util function to manipulate the tables data for example (some `mapColumn` or anything generic enough)
