### ISSUE TITLE
Would the text children be abolished in future slate-edit-table?

### ISSUE THREAD

**Issue by zhujinxuan** [GitbookIO/slate-edit-table#68]
Hi, I have just seen there is a new branch named `allow-block-children`.  I am wondering two things:

1. Does that mean text children will be abolished in the future `slate-edit-table`?
2. Would the future `slate-edit-table` support nested table?

**Comment by Soreine** [comment]
Yes, the goal is to support blocks in cells. I would like to keep the ability to have text children only. It should support nested tables too. I'll open a PR if you wish, for visibility. But for now it is working for older versions of slate (we haven't upgraded yet). It will be updated afterward.

**Comment by Soreine** [comment]
I am also removing any align concept from the plugin. But I'm adding utilities to make it easy to implement in the userland.

**Comment by Soreine** [comment]
https://github.com/GitbookIO/slate-edit-table/pull/69

**Comment by Soreine** [comment]
Don't hesitate to suggest utils useful to you
