### ISSUE TITLE
Option to override default cell node instead of text

### ISSUE THREAD

**Issue by joehua87** [GitbookIO/slate-edit-table#7]
- So that we can add image, multiline text into table cell
- My suggestion: Add defaultCellNode to insertTable opts & pass down it into createCell function

```
insertTable(opts, transform, columns = 2, rows = 2)
```

If opts contains the `defaultCellNode` node, it will render table-cell's nodes as

```
nodes: [node]
```

else it will render

```
nodes: [
    Slate.Raw.deserializeText({
        kind: 'text',
        text: text
    }, { terse: true })
]
```

**Comment by jasonphillips** [comment]
This may be more than you had in mind, but I needed deep tables capable of all block formatting (lists, etc) and finally just forked this project and rebuilt it for that purpose.

https://github.com/jasonphillips/slate-deep-table

It handles any kind of deep content, and the tests / transforms / schema rules have all be converted to understand this kind of content. I'd have made it a PR but it seems to go beyond the current scope or intentions of this repo.

**Comment by Soreine** [comment]
Indeed, this goes beyond the current scope of this plugin.
`slate-deep-table`, made by @jasonphillips , seems to be a great alternative 👍
