### ISSUE TITLE
Enter key doesn't split blocks

### ISSUE THREAD

**Issue by Zhouzi** [GitbookIO/slate-edit-table#71]
Pressing enter in a cell doesn't split the block but inserts a new row.

**Comment by CameronAckermanSEL** [comment]
This is (i think) pretty simple to add and actually really important. You should just be able to remove the onEnter handler and allow slate to handle the enter event and it should work as expected. At worst, an onEnter handler that instead inserts a new block with the default type will do the job, too.

**Comment by CameronAckermanSEL** [comment]
Nevermind, the arrow key positioning logic would also need to change. That's not too hard either but it is extra work.

**Comment by Soreine** [comment]
You're right it's as simple as removing code from onKeyDown. It's just sad
because it makes it harder to edit a table using the keyboard.

**Comment by CameronAckermanSEL** [comment]
Truth, I think the biggest lost would be a good keyboard shortcut for adding a new row below the current selection (something we've removed in our fork), but other editors don't seem to have this out of the box. What about alt+enter for adding a new row as an alternative?

**Comment by Zhouzi** [comment]
We can probably take inspiration from common sheets tools: enter "creates" a new row while shift+enter creates a new "paragraph".

**Comment by CameronAckermanSEL** [comment]
That might be how sheets behaves, but I think that's intended to be a parallel to excel and a "data grid" from excel is conceptually different than a "table" in, say, word or google docs. I also think that most users indirectly consuming this plugin would expect for the enter behavior to behave like word or google docs, or more generally like a document editor as opposed to a spreadsheet editor.

In google docs and word, enter creates a line break within the cell. Neither editor has a keyboard shortcut for creating a new row though, but ctrl+enter and alt+enter are not taken keyboard shortcuts there.

**Comment by zhujinxuan** [comment]
Why not put an pluginOption:

```
hotkeys: {
  "new-row": "enter",
  linebreak: "mod+enter",
  "next-cell": ....
}
```

**Comment by CameronAckermanSEL** [comment]
I like that idea too :)
